[package]

name = "libfriendship"
version = "0.0.1"
authors = [ "Colin Wallace <wallacoloo@gmail.com>" ]

license = "MIT"

[dependencies]
num = "*"
# Serialization
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.online_dag]
git = "https://github.com/wallacoloo/online_dag.git"

[dependencies.pwline]
git = "https://github.com/wallacoloo/rust-pwline.git"
