[package]

name = "libfriendship"
version = "0.0.1"
authors = [ "Colin Wallace <wallacoloo@gmail.com>" ]

license = "MIT"

[dependencies]
sha2 = "0.5"
# Serialization
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.4"
url_serde = "0.1"

[dependencies.pwline]
git = "https://github.com/wallacoloo/rust-pwline.git"
