[package]

name = "libfriendship"
version = "0.0.1"
authors = [ "Colin Wallace <wallacoloo@gmail.com>" ]

license = "MIT"

[dependencies]
num-complex = "0.1.33"

[dependencies.online_dag]
git = "https://github.com/wallacoloo/online_dag.git"
